import { useEffect,useState } from 'react'
import { Dumbbell,Send } from 'lucide-react'
import { useSessao } from '../lib/auth'
import { useHistoricoTreinos } from '../lib/historicoTreinos'
import { enviarMensagem,listarMensagens,type Mensagem } from '../lib/social/mensagens'

export function Chat({conversaId,grupoId}:{conversaId?:string;grupoId?:string}){
 const {sessao}=useSessao(),[mensagens,setMensagens]=useState<Mensagem[]>([]),[texto,setTexto]=useState(''),[erro,setErro]=useState<string|null>(null),[enviando,setEnviando]=useState(false),[escolhendo,setEscolhendo]=useState(false)
 const historico=useHistoricoTreinos(sessao?.user.id,10),destino={conversaId,grupoId}
 async function carregar(){try{setErro(null);setMensagens(await listarMensagens(destino))}catch{setErro('Não foi possível carregar as mensagens.')}}
 useEffect(()=>{let cancelado=false;const atualizar=()=>listarMensagens({conversaId,grupoId}).then(dados=>{if(!cancelado)setMensagens(dados)}).catch(()=>{if(!cancelado)setErro('Não foi possível carregar as mensagens.')});void atualizar();const intervalo=window.setInterval(()=>void atualizar(),8000);return()=>{cancelado=true;window.clearInterval(intervalo)}},[conversaId,grupoId])
 async function enviar(treinoId?:string){if(!texto.trim()&&!treinoId)return;setEnviando(true);try{await enviarMensagem(destino,texto,treinoId);setTexto('');setEscolhendo(false);await carregar()}catch{setErro('Não foi possível enviar a mensagem.')}finally{setEnviando(false)}}
 return <section className="mt-5"><div className="max-h-[52vh] min-h-64 space-y-3 overflow-y-auto border-y border-line/60 py-4">{mensagens.length===0&&!erro&&<p className="py-12 text-center text-sm text-ink-2">Comece a conversa.</p>}{mensagens.map(m=><div key={m.id} className={`flex ${m.remetenteId===sessao?.user.id?'justify-end':'justify-start'}`}><div className={`max-w-[82%] rounded-2xl px-4 py-3 ${m.remetenteId===sessao?.user.id?'bg-brand text-white':'bg-card text-ink'}`}><p className="mb-1 text-[10px] font-semibold opacity-70">{m.nome}</p>{m.texto&&<p className="whitespace-pre-wrap break-words text-sm">{m.texto}</p>}{m.treinoId&&<div className="mt-2 flex items-center gap-2 border-t border-white/20 pt-2 text-xs font-semibold"><Dumbbell size={15}/> Treino marcado</div>}</div></div>)}</div>{erro&&<p className="mt-3 text-sm text-down">{erro}</p>}{escolhendo&&<div className="mt-3 max-h-44 overflow-y-auto rounded-xl border border-line bg-card p-2">{historico.carregando?<p className="p-3 text-xs text-ink-2">Carregando treinos...</p>:historico.treinos.map(t=><button key={t.id} onClick={()=>void enviar(t.id)} className="min-h-12 w-full border-b border-line/60 px-2 text-left text-sm">{t.nome}</button>)}</div>}<div className="mt-3 flex items-end gap-2"><button onClick={()=>setEscolhendo(v=>!v)} aria-label="Marcar treino" className="flex size-12 shrink-0 items-center justify-center rounded-xl border border-line text-brand"><Dumbbell size={18}/></button><textarea value={texto} maxLength={1000} onChange={e=>setTexto(e.target.value)} rows={1} placeholder="Escreva uma mensagem" className="min-h-12 flex-1 resize-none rounded-xl border border-line bg-card p-3 text-sm outline-none focus:border-brand"/><button disabled={enviando} onClick={()=>void enviar()} aria-label="Enviar mensagem" className="flex size-12 shrink-0 items-center justify-center rounded-xl bg-brand text-white disabled:opacity-50"><Send size={18}/></button></div></section>
}
