-- VIVECI — BLOCO 2: EXERCÍCIOS (56 exercícios, todos os grupos)
-- Cole no SQL Editor do Supabase e clique em Run.

insert into exercicios (nome, grupo_muscular, grupos_secundarios, nivel, equipamento, is_composto) values
('Supino reto com barra','Peito','{Tríceps,Ombros}','Iniciante','Barra',true),
('Supino inclinado com halteres','Peito','{Tríceps,Ombros}','Iniciante','Halter',true),
('Supino declinado com barra','Peito','{Tríceps}','Intermediário','Barra',true),
('Crucifixo com halteres','Peito','{Ombros}','Iniciante','Halter',false),
('Crossover na polia','Peito','{}','Intermediário','Cabo',false),
('Voador na máquina','Peito','{}','Iniciante','Máquina',false),
('Flexão de braço','Peito','{Tríceps,Abdômen}','Iniciante','Peso corporal',true),
('Flexão inclinada','Peito','{Tríceps}','Iniciante','Peso corporal',true),
('Supino com elástico','Peito','{Tríceps}','Iniciante','Elástico',true),
('Puxada frontal na polia','Costas','{Bíceps}','Iniciante','Cabo',true),
('Remada curvada com barra','Costas','{Bíceps,Posterior}','Intermediário','Barra',true),
('Remada baixa na polia','Costas','{Bíceps}','Iniciante','Cabo',true),
('Remada unilateral com halter','Costas','{Bíceps}','Iniciante','Halter',true),
('Barra fixa','Costas','{Bíceps}','Avançado','Peso corporal',true),
('Pulldown com corda','Costas','{}','Intermediário','Cabo',false),
('Levantamento terra','Costas','{Posterior,Glúteos,Quadríceps}','Avançado','Barra',true),
('Remada com elástico','Costas','{Bíceps}','Iniciante','Elástico',true),
('Desenvolvimento com halteres','Ombros','{Tríceps}','Iniciante','Halter',true),
('Desenvolvimento militar com barra','Ombros','{Tríceps}','Intermediário','Barra',true),
('Elevação lateral','Ombros','{}','Iniciante','Halter',false),
('Elevação frontal','Ombros','{}','Iniciante','Halter',false),
('Crucifixo inverso','Ombros','{Costas}','Intermediário','Halter',false),
('Encolhimento de ombros','Ombros','{}','Iniciante','Halter',false),
('Elevação lateral com elástico','Ombros','{}','Iniciante','Elástico',false),
('Rosca direta com barra','Bíceps','{}','Iniciante','Barra',false),
('Rosca alternada com halteres','Bíceps','{}','Iniciante','Halter',false),
('Rosca martelo','Bíceps','{}','Iniciante','Halter',false),
('Rosca scott','Bíceps','{}','Intermediário','Máquina',false),
('Rosca concentrada','Bíceps','{}','Iniciante','Halter',false),
('Rosca com elástico','Bíceps','{}','Iniciante','Elástico',false),
('Tríceps na polia com barra','Tríceps','{}','Iniciante','Cabo',false),
('Tríceps corda','Tríceps','{}','Iniciante','Cabo',false),
('Tríceps testa','Tríceps','{}','Intermediário','Barra',false),
('Tríceps francês com halter','Tríceps','{}','Intermediário','Halter',false),
('Mergulho no banco','Tríceps','{Peito}','Iniciante','Peso corporal',true),
('Tríceps coice','Tríceps','{}','Iniciante','Halter',false),
('Agachamento livre','Quadríceps','{Glúteos,Posterior}','Intermediário','Barra',true),
('Leg press','Quadríceps','{Glúteos}','Iniciante','Máquina',true),
('Cadeira extensora','Quadríceps','{}','Iniciante','Máquina',false),
('Afundo com halteres','Quadríceps','{Glúteos}','Iniciante','Halter',true),
('Agachamento búlgaro','Quadríceps','{Glúteos}','Intermediário','Halter',true),
('Agachamento livre sem peso','Quadríceps','{Glúteos}','Iniciante','Peso corporal',true),
('Hack machine','Quadríceps','{Glúteos}','Intermediário','Máquina',true),
('Mesa flexora','Posterior','{}','Iniciante','Máquina',false),
('Stiff com barra','Posterior','{Glúteos}','Intermediário','Barra',true),
('Cadeira flexora','Posterior','{}','Iniciante','Máquina',false),
('Good morning','Posterior','{Glúteos}','Avançado','Barra',true),
('Elevação pélvica','Glúteos','{Posterior}','Iniciante','Barra',true),
('Cadeira abdutora','Glúteos','{}','Iniciante','Máquina',false),
('Coice na polia','Glúteos','{Posterior}','Iniciante','Cabo',false),
('Ponte de glúteo no solo','Glúteos','{Posterior}','Iniciante','Peso corporal',false),
('Panturrilha em pé','Panturrilha','{}','Iniciante','Máquina',false),
('Panturrilha sentado','Panturrilha','{}','Iniciante','Máquina',false),
('Panturrilha no step','Panturrilha','{}','Iniciante','Peso corporal',false),
('Abdominal supra','Abdômen','{}','Iniciante','Peso corporal',false),
('Prancha isométrica','Abdômen','{Ombros}','Iniciante','Peso corporal',false),
('Elevação de pernas','Abdômen','{}','Intermediário','Peso corporal',false),
('Abdominal remador','Abdômen','{}','Intermediário','Peso corporal',false),
('Prancha lateral','Abdômen','{}','Iniciante','Peso corporal',false);
